### ISSUE TITLE
Trouble installing/loading isoprocessor in R version 3.6.0

### ISSUE THREAD

**Issue by danote** [isoverse/isoprocessor#43]
> devtools::install_github("isoverse/isoprocessor")
Downloading GitHub repo isoverse/isoprocessor@master
✔  checking for file ‘/private/var/folders/pw/9fk_chms0jl85nfldy5rgfyc0000gn/T/RtmpGRq76b/remotesd2f97f3ca6a2/isoverse-isoprocessor-d728877/DESCRIPTION’ (338ms)
─  preparing ‘isoprocessor’: (410ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘isoprocessor_0.4.0.1.tar.gz’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘isoprocessor/docs/articles/gc_irms_example_carbon_files/figure-html/example_chromatograms_with_peaks-1.png’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘isoprocessor/docs/articles/gc_irms_example_carbon_files/figure-html/first_look_sample_and_standard_peaks-1.png’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘isoprocessor/docs/articles/gc_irms_example_carbon_files/figure-html/global_calibration_coefficients-1.png’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘isoprocessor/docs/articles/gc_irms_example_carbon_files/figure-html/global_calibration_residuals-1.png’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘isoprocessor/docs/articles/gc_irms_example_carbon_files/figure-html/single_analysis_calibration_coefficients-1.png’
   
* installing *source* package ‘isoprocessor’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for ‘isoreader’:
 .onLoad failed in loadNamespace() for 'isoreader', details:
  call: NULL
  error: (converted from warning) Unquoting language objects with `!!!` is deprecated as of rlang 0.4.0.
Please use `!!` instead.

  # Bad:
  dplyr::select(data, !!!enquo(x))

  # Good:
  dplyr::select(data, !!enquo(x))    # Unquote single quosure
  dplyr::select(data, !!!enquos(x))  # Splice list of quosures

This warning is displayed once per session.
Error: package ‘isoreader’ could not be loaded
Execution halted
ERROR: lazy loading failed for package ‘isoprocessor’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/isoprocessor’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/pw/9fk_chms0jl85nfldy5rgfyc0000gn/T//RtmpGRq76b/filed2f966e016f0/isoprocessor_0.4.0.1.tar.gz’ had non-zero exit status

**Comment by sebkopf** [comment]
@danote this issue was a mixed bag between isoreader and isoprocessor. You'll have to upgrade to the newest versions of both to be 3.6.0 compatible
