### ISSUE TITLE
iso_set_peak_table_automatically_from_vendor_data_table not working on mac

### ISSUE THREAD

**Issue by Rhavranek** [isoverse/isoprocessor#85]
Hi Seb,

I'm working through Brett's code lookign for problems, and I'm having trouble getting through on of the early chunks. (The exact rmd I'm working on is called - rmarkdown_5_ea_irms_example_Gasbench_greatness

when I run:
```
 # process peak table
iso_files_w_peak_table <- iso_files_raw %>% 
  # set peak table from vendor data table
  iso_set_peak_table_automatically_from_vendor_data_table() %>% 
  # convert units from mV to V for amplitudes and area
  iso_convert_peak_table_units(V = mV, Vs = mVs) 
```
 I get the error: Error in apply_software_files_ids[[i, "func"]](iso_files[apply_software_files_ids[[i,  : 
  attempt to apply non-function

**Comment by sebkopf** [comment]
@Rhavranek : thanks for reporting this, please take a look at https://github.com/isoverse/news/issues/2
